volumes:
    conflux-db-data:
        name: conflux-db-data

services:
  conflux-db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
        POSTGRES_USER: conflux-dev
        POSTGRES_PASSWORD: conflux-dev
        POSTGRES_DB: conflux-dev
    ports:
        - 5432:5432
    volumes:
        -   conflux-db-data:/var/lib/postgresql/data
