// This program has been developed by students from the bachelor Computer Science at Utrecht
// University within the Software Project course.
// 
// © Copyright Utrecht University (Department of Information and Computing Sciences)

using Pgvector;

namespace Conflux.Domain.Logic.Services;

/// <summary>
/// Service for generating semantic embeddings from text content
/// </summary>
public interface IEmbeddingService
{
    /// <summary>
    /// Generates a semantic embedding vector from the given text
    /// </summary>
    /// <param name="text">The text to embed</param>
    /// <param name="languageCode">Optional language hint (e.g., "eng", "nld")</param>
    /// <returns>A vector embedding</returns>
    Task<Vector> GenerateEmbeddingAsync(string text);

    /// <summary>
    /// Generates embeddings for multiple texts in a batch for efficiency
    /// </summary>
    /// <param name="texts">The texts to embed</param>
    /// <param name="languageCode">Optional language hint</param>
    /// <returns>Vector embeddings for each text</returns>
    Task<Vector[]> GenerateEmbeddingsAsync(string[] texts);

    /// <summary>
    /// Gets the dimension size of the embeddings generated by this service
    /// </summary>
    int EmbeddingDimension { get; }
}
