name: publish-typescript-client
on:
    push:
        branches:
            - main
    workflow_dispatch:
        
env:
    ASPNETCORE_ENVIRONMENT: "Workflow"
    DOTNET_ENVIRONMENT: "Workflow"
    SRAM_CLIENT_SECRET: ${{ secrets.SRAM_CLIENT_SECRET }}

jobs:
    publish-typescript-client:
        runs-on: ubuntu-latest
        permissions:
            contents: write # to be able to publish a GitHub release
            pull-requests: write # to be able to comment on released pull requests
            packages: write # to publish to the registry
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '9.x'
            
            -   uses: actions/setup-node@v4
            
            -   name: Install NSwag CLI
                run: |
                    dotnet tool install --global NSwag.ConsoleCore
            
            -   name: Build project
                run: dotnet build --no-incremental
            
            -   name: Run project
                run: |
                    cd Conflux.API
                    dotnet run &

                    echo "Waiting for Swagger API to start..."
                    for i in {1..20}; do
                      if curl --silent http://localhost:8000/swagger/v1/swagger.json > /dev/null; then
                        echo "API is up!"
                        break
                      fi
                      echo "Waiting ($i)..."
                      sleep 2
                    done
            
            -   name: Generate API-client
                run: |
                    cd Conflux.API
                    nswag run
            
            -   name: Build NPM package
                run: |
                    cd conflux-api-client
                    npm i
                    npm run build
            
            -   name: Publish NPM package
                run: |
                    cd conflux-api-client
                    npx semantic-release
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    
                    
            